name: Terraform Basic

on:
  push:
    branches:
      - main

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

          #  DEV DEPLOY
      - name: Terraform Init Dev
        if: github.ref == 'refs/heads/dev'
        run: terraform init -backend-config="backend-dev.conf"

      - name: Terraform Plan Dev
        if: github.ref == 'refs/heads/dev'
        run: terraform plan -var-file="dev.tfvars"


      #  PROD DEPLOY
      - name: Terraform Init Prod
        if: github.ref == 'refs/heads/main'
        run: terraform init -backend-config="backend-prod.conf"

      - name: Terraform Plan Prod
        if: github.ref == 'refs/heads/main'
        run: terraform plan -var-file="prod.tfvars"